markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Jesús Díaz
url: http://hispano.github.io/jesusdg/
description: A fantastic blog that is fantastic.
twitter: jesusdiazgt
github: Hispano
gravatar_url: http://gravatar.com/avatar/8208786a2a94134f3efe934bda8796ff